  
version: '3'
services:
  app:
    container_name: app-watcher
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - watcher-network
    command: bash -c "npm install && npm run dev"
    env_file:
      - ./.env
    ports:
      - '3000:3000'

networks:
  watcher-network:

  